spring:
  application:
    name: tlias-web-manager
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 114514

#Mybatis的相关配置
mybatis:
  configuration:
    log-imp: org.apche.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath/*.xml


